### ISSUE TITLE
please Help me - can i use this on centos 6

### ISSUE THREAD

**Issue by odoacer** [kyprizel/testcookie-nginx-module#28]
hi thanks for your job

i want use this great Anti-DDoS Module 
but not working on my system
my system is Centos 6 + Nginx 1.4.4
error message is this

$ /etc/init.d/nginx start
Starting nginx: /bin/bash: line 1:  2903 Segmentation fault      (core dumped) /usr/sbin/nginx -c /etc/nginx/nginx.conf
                                                           [FAILED]

nginx configure option 

./configure --user=nobody --group=nobody --prefix=/usr/share --sbin-path=/usr/sbin/nginx \
--conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log \
--pid-path=/var/log/run/nginx.pid --lock-path=/var/log/lock/subsys/nginx --with-http_ssl_module --with-http_realip_module \
--with-http_addition_module --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_gzip_static_module \
--with-http_stub_status_module --with-http_perl_module --with-mail_ssl_module --with-http_mp4_module --with-mail \
--with-openssl=/usr/local/src/openssl-0.9.8y --with-openssl-opt=enable-tlsext --add-module=/usr/local/src/nginx-sflow-module-0.9.8 \
--add-module=/usr/local/src/modsecurity-2.8.0/nginx/modsecurity/ \
--add-module=/usr/local/src/testcookie-nginx-module

thanks for your Help

**Comment by kyprizel** [comment]
use
gdb /usr/sbin/nginx
to understand which module leads to segfault.
