### ISSUE TITLE
User sometimes get the page cookies.html, despite the fact that cookies are enabled.

### ISSUE THREAD

**Issue by jok40** [kyprizel/testcookie-nginx-module#29]
If the user opened the page and refresh it from time to time, then in the end he will get the page cookies.html, despite the fact that cookies are enabled.

Example:
5.76.194.133 - [11/Jul/2015:13:01:23 +0600] "GET /page.php?lng=1 HTTP/1.1" 307 186
5.76.194.133 - [11/Jul/2015:13:01:25 +0600] "GET /page.php?lng=1&attempt=1 HTTP/1.1" 200 12740
5.76.194.133 - [11/Jul/2015:14:33:38 +0600] "GET /page.php?lng=1&attempt=1 HTTP/1.1" 307 186
5.76.194.133 - [11/Jul/2015:14:33:41 +0600] "GET /page.php?lng=1&attempt=2 HTTP/1.1" 200 12740
5.76.194.133 - [11/Jul/2015:20:30:31 +0600] "GET /page.php?lng=1&attempt=2 HTTP/1.1" 307 186
5.76.194.133 - [11/Jul/2015:20:30:32 +0600] "GET /page.php?lng=1&attempt=3 HTTP/1.1" 200 12740
5.76.194.133 - [11/Jul/2015:20:38:17 +0600] "GET /page.php?lng=1&attempt=3 HTTP/1.1" 307 186
5.76.194.133 - [11/Jul/2015:20:38:17 +0600] "GET /cookies.html?backurl=http://***.com/page.php?lng=1&attempt=3 HTTP/1.1" 200 289

How to fix this issue?

**Comment by Nguyen-Dang-Thu** [comment]
Can you please provide some config for nginx?

**Comment by jok40** [comment]
I have already solved this issue. In Apache I did redirect to URL without the last parameter - "&attempt=X".
