### ISSUE TITLE
Where to find aes.min.js?

### ISSUE THREAD

**Issue by techpulse** [kyprizel/testcookie-nginx-module#33]
All the versions I tried does not seem to work.

**Comment by Mecanik** [comment]
It works, problem is with the module for nginx, you have to define it differently then on the examples here... I`m gonna search where I put mine, and give it to you. Even though, it`s a shit module bro. I used it in commercial enviroment and I failed.

**Comment by techpulse** [comment]
I don't have any alternatives, wish someone could re-make it and make it more secure and more options like check if mouse moves etc.

**Comment by techpulse** [comment]
Def not good for hosting services, blocks API's, Google and much more.. White listing isn't really good.

**Comment by Mecanik** [comment]
It does not block anything if you define the IP list, the problem is the redirect issue, sometimes it just throwes the user to the callback URL for no reason...

**Comment by techpulse** [comment]
I've not had that issue, unless they are using invalid browser or phones that doesn't accept certain headers.

**Comment by Mecanik** [comment]
You will have, my users where only on chrome or mozzila, and they send me
the screenshots...

**Comment by techpulse** [comment]
Using what, javascript or cookie headers?

**Comment by Mecanik** [comment]
Anything... tried everything

**Comment by techpulse** [comment]
Something wrong with your installation then, never had such issue.

**Comment by Mecanik** [comment]
Are you sure ? double check :)

**Comment by glintik** [comment]
Mecanik, check one more time, should work in proper install.

**Comment by techpulse** [comment]
I used it over a year buddy :) Only issue i have is that some browsers on phone can't accept the cookie it sets.

**Comment by Mecanik** [comment]
I compile my own version, with all the existing modules, I have 100%
pagespeed on google, and I am telling you it`s fucked... search on google
and see there where others with this issue

**Comment by techpulse** [comment]
Not too sure why you closed it @kyprizel - still haven't solved my issue :)

**Comment by techpulse** [comment]
none of the aes versions i tried working, says either error with slowaes or other errors.

**Comment by kyprizel** [comment]
Please, try to google for AES implementation, it's out of this modules code.

**Comment by techpulse** [comment]
i mean i used your example, and when the example isn't working then idk

**Comment by techpulse** [comment]
no update @kyprizel ? i really want this working :'(

**Comment by kyprizel** [comment]
Sorry, as I can see - the problem is on your side.
