### ISSUE TITLE
testcookie fails for certain IP addresses

### ISSUE THREAD

**Issue by bryangwilliam** [kyprizel/testcookie-nginx-module#34]
I have been trying out this module for a little while now, and just yesterday noticed some rather strange behavior. When I enable testcookie for a particular location there are certain clients that always fail the test no matter what. It appears to be based on the session identifier, because I am able to get it working by either changing the client's IP address or by changing testcookie_session to something other than $remote_addr (in this case, I used $remote_addr$http_user_agent as suggested in the docs). My concern is that while I may have gotten those particular clients to work, I don't have a good way to tell if I just shifted the problem somewhere else. Is it possible there is a certain cookie value that fails every time?

At the time we noticed this, there were 3 distinct IPs that experienced the problem, but of course there were likely more since the odds of us having the only three addresses that do not work is pretty slim. Unfortunately I don't have a simple way to test every address/useragent combination to see what works and what does not. Any ideas what might be going on?

**Comment by imgonnagityou** [comment]
I'm seeing the same problem, just not sure what is causing it.

The users get continually challenged over multiple browsers, and we actually see the cookie being set but just doesn't want to let them through.

**Comment by kyprizel** [comment]
can you write a traffic dump (pcap)?

**Comment by imgonnagityou** [comment]
sorry for the delay, please see attached.

at frame 8 is where the challenge begins, and in a working client i normally see the next frame return a http 302, but in the clients that fail it returns a http 200 and ultimately sends them to the fallback url.

[dump.zip](https://github.com/kyprizel/testcookie-nginx-module/files/118648/dump.zip)

**Comment by kyprizel** [comment]
Your slowaes is not patched:
https://s3.amazonaws.com/h280s5lw/aes.min.js
https://github.com/kyprizel/testcookie-nginx-module/blob/master/util/aes.patch

have you tested with a patch?

**Comment by imgonnagityou** [comment]
I was only able to verify with one of my users (that was failing before) that the patched aes no longer gives them the continued failure and that is a good start.  

Thank you for suggestion.
