### ISSUE TITLE
Попытки открытия страницы

### ISSUE THREAD

**Issue by mdpuma** [kyprizel/testcookie-nginx-module#36]
Использую testcookie с javascript обработкой.

Заметил в логах на серверах с данным модулем интересное поведение. При открытий браузера Firefox 44 версий, бывает так, что ни одна страница не открыта, но в тоже время, попытки открытия сайтов в логах. Позже нашёл что это из за списка "часто посещаемых страниц".

По проведённому анализу, при таких попытках запроса, javascript работает, но куки не принимает, и в итоге получается цикл бесконечный, который может заставить людей усомнится в модуле.

Не плохо было бы добавить заметку об этом. Ещё, предлагаю, пропускать запрос в обход модуля после определённого количества попыток.

**Comment by pavel-odintsov** [comment]
Привет!

Странный кейс, на самом деле. Тут вопрос к FF почему он не обрабатывает js в этом случае. Какой-либо skype предпросмотр, скорее всего, поведет себя ровно также. Как и любой поисковик, если его не вайтлистнули :)

**Comment by kyprizel** [comment]
Пропускать запрос в обход модуля  - не вариант.
Почему FF не принимает куки  - нужно разбираться.

**Comment by pavel-odintsov** [comment]
Абсолютно согласен. Пропускать в обход - открывать ворота неприятелю.

**Comment by mdpuma** [comment]
Ну хоть я не единственный кто заметил недочёт :)

**Comment by pavel-odintsov** [comment]
Я думаю силами конфигурации можно сделать обходник, если очень хочется используя testcookie_pass для отключения валидации для заданного локейшена / юзер агента.

**Comment by kyprizel** [comment]
Проблема в FF, не в модуле
