### ISSUE TITLE
How to build module as dynamic?

### ISSUE THREAD

**Issue by pavel-odintsov** [kyprizel/testcookie-nginx-module#37]
Hello!

I saw this feature in commit log :) That's really cool! But could you share some docs about building it?

**Comment by kyprizel** [comment]
Just

%%
make clean
./configure --with-debug \
                        --with-http_ssl_module \
                        --add-dynamic-module=/path/to/testcookie-nginx-module/
make
%%

see
https://github.com/kyprizel/testcookie-nginx-module/#installation

**Comment by pavel-odintsov** [comment]
Thanks! Nice!
