### ISSUE TITLE
Ability to specify custom http code code for testcookie_redirect_via_refresh enabled mode

### ISSUE THREAD

**Issue by pavel-odintsov** [kyprizel/testcookie-nginx-module#38]
Hello!

Thanks for nice toolkit! 

We are using testcookie_redirect_via_refresh mode and we want to notify search engines to try later (with 503 code) when test cookie enabled. We are huge site and Search engines are very important for us.

We know about white list but it's not unified way and we could miss some subnet of SE bots and they will index broken content (page with redirection code) instead of real content.

We are using test cookie mitigation only when attack arrives and switch it of when it finishes.  So we want some way to specify custom http code and ask SE bots to check us later (when attack finishes).

What do you think about this idea?

**Comment by kyprizel** [comment]
no problem - i'll add testcookie_refresh_status directive.

**Comment by kyprizel** [comment]
Please, check
https://github.com/kyprizel/testcookie-nginx-module/commit/afd9e7ac316d3e8d77d7a2f13dc3d8f1f169881a

**Comment by pavel-odintsov** [comment]
Perfect! Working like a charm! All browsers I've checked process 503 code well (Chrome/Mac, Safari/Mac, Mozilla/Mac).
