### ISSUE TITLE
Возможность задать статус для кастомного шаблона ответа

### ISSUE THREAD

**Issue by akhalikov** [kyprizel/testcookie-nginx-module#40]
Для конфигурации с кастомным HTML шаблоном хотелось бы иметь возможность задать статус HTTP ответа. Сейчас статус по-умолчанию 200. Потенциально это может привести к тому что поисковые боты, не включенные в список testcookie_whitelist, могут закэшировать кастомную страницу.

**Comment by kyprizel** [comment]
https://github.com/kyprizel/testcookie-nginx-module/blob/master/Changelog
