### ISSUE TITLE
Fail2ban

### ISSUE THREAD

**Issue by SebastianM4** [kyprizel/testcookie-nginx-module#41]
I love this module, its just awesome i really love it, but i also need fail2ban to block the tons of ip addresses which are sending tons of request. Before i did it over fail2ban and req-limit in nginx, worked fine but now im facing an issue. My website loads tons of different files when a legit users views my board, so i placed the req limit in the php location, since each request only loaded 1 php file. Now i dont find any way to use the req-limit properly with the cookie check. As example:

Im requesting domain.com/index.php and the cookie check page shows up instead of the index.php, but the access log, logs the index.php request. Now the req-limit module would still work, but as example if they request domain.com just, the cookie page will also show up and the req-limit wont work, since its only in the php location. Im unable to place it in the / location, because it would block legit users later on, is there any way to send them as example to domain.com/cookie.html when the cookie is getting checked&set?

**Comment by kyprizel** [comment]
No, it works in different way
