### ISSUE TITLE
A Little help with installation steps?!

### ISSUE THREAD

**Issue by systemroot** [kyprizel/testcookie-nginx-module#43]
I was trying to configure testcookies with nginx for 2-3-4-5 days :angry: 
and every time i have fail with this. 
example now i try to install testcookies with nginx v1.8.1 
looks like installation is done without any error. But..
![](http://image.prntscr.com/image/65677965971c47a8806aed7b572a68a2.png)
<pre>
root@nginx:/usr/local/nginx/sbin# ./nginx -V
nginx version: nginx/1.8.1
built by gcc 4.8.4 
built with OpenSSL 1.0.1f 6 Jan 2014
TLS SNI support enabled
configure arguments: --add-module=testcookie-nginx-module

</pre>
<pre>
root@nginx:/usr/local# find ~ nginx/
nginx/
nginx/logs
nginx/logs/nginx.pid
nginx/logs/access.log
nginx/logs/error.log
nginx/conf
nginx/conf/nginx.conf
nginx/conf/fastcgi_params.default
nginx/conf/uwsgi_params
nginx/conf/uwsgi_params.default
nginx/conf/fastcgi_params
nginx/conf/nginx.conf.default
nginx/conf/mime.types.default
nginx/conf/koi-utf
nginx/conf/scgi_params.default
nginx/conf/fastcgi.conf.default
nginx/conf/fastcgi.conf
nginx/conf/win-utf
nginx/conf/koi-win
nginx/conf/scgi_params
nginx/conf/mime.types
nginx/proxy_temp
nginx/fastcgi_temp
nginx/sbin
nginx/sbin/nginx
nginx/html
nginx/html/50x.html
nginx/html/index.html
nginx/client_body_temp
nginx/uwsgi_temp
nginx/scgi_temp
</pre>
Nginx is ON  but  i can't find folder "modules" or **ngx_http_testcookie_filter_module.so** 
i have use apache every time :confused: and i don't know too much about nginx anyone can please help me how to install this?! And which version of nginx is more better to use for testcookies?!

Thanks.

**Comment by Jaxkr** [comment]
Try with newer nginx. 1.9.1 as recommended in the guide. Also make sure the path to testcookie is correct while compiling.

**Comment by systemroot** [comment]
@Jaxkr  Thank You. I read online some doc's how to compile Nginx, i add module testcookies, 
And now is working :clap:
