### ISSUE TITLE
Вопрос про параметр testcookie_internal

### ISSUE THREAD

**Issue by altexdim** [kyprizel/testcookie-nginx-module#45]
https://github.com/kyprizel/testcookie-nginx-module#testcookie_internal

В описании написано, что POST requests will be bypassed. Скорее всего это опечатка. 
Но что именно означает, что внутренние редиректы выключены по-уполчанию из-за оптимизации? На каждый внутренний редирект вызывается проверка куки, и вместо одного раза, кука проверяется столько раз, сколько происходит редиректов плюс один? И каждый раз выполняется симметричное шифрование на каждой проверке? Или всё же зашифрованное значение кешируется?

> testcookie_internal
> syntax: testcookie_internal (on|off);
> default: off
> context: http, server, location
> Process only GET requests, POST requests will be bypassed. Enable testcookie check for internal redirects (disabled by default for optimization purposes!), useful for this type of configs:
> rewrite ^/(.*)$ /index.php?$1 last;

Заранее спасибо за ответ. И спасибо за ваш вклад в opensource.

**Comment by kyprizel** [comment]
Да, это опечатка. Спасибо - исправил.
По умолчанию для внутренних редиректов проверка куки не вызывается.
Но т.к. модуль работает в ACCESS PHASE, которая происходит после REWRITE, то при внутренних редиректах может появиться необходимость ее включить. В этом случае проверка будет выполняться на каждый редирект, но значение ключей и куки для сравнения будет кешироваться.
