### ISSUE TITLE
rewrite + internal on causes duplicate query string

### ISSUE THREAD

**Issue by costpermille** [kyprizel/testcookie-nginx-module#47]
If I have `        rewrite ^/blog/([0-9]+)$ /blog.php?post_id=$1 last;`, enabling internal will make the redirected URL `/blog/1?post_id=1&attempt=1`, which internally turns into `/blog.php?post_id=1&post_id=1&attempt=1`.

Is it possible to set option to not append anything to the request uri other than attempt testcookie arg?

**Comment by kyprizel** [comment]
there is special option:
https://github.com/kyprizel/testcookie-nginx-module#testcookie_internal
