### ISSUE TITLE
Cookie doesnt get setted

### ISSUE THREAD

**Issue by d3dx9** [kyprizel/testcookie-nginx-module#48]
Hi!

At some users it happens in every browser that no cookie gets setted.

It looks like, the plugin doesnt add the iv and key to the source code. Any idea how to fix it?

**Comment by kyprizel** [comment]
Check your config.

**Comment by d3dx9** [comment]
So you think? 

The config was actually right, but it looks like it doesn't like every ip or something else.

It actually is a network error not a cookie error.

**Comment by Mecanik** [comment]
I agree with @d3dx9  here, because I tested this on production environment many times, and there is an issue that happens to some users.

Cannot say for sure what, without any DEBUG logs or additional options... especially without any info from the developer...

**Comment by Mecanik** [comment]
Any follow up regarding this ? I can confirm this problem 100%, after testing months and months with different configuration and browsers and IP's.

A fix or guide for the problem would be nice....

**Comment by kyprizel** [comment]
Is it a guees you config game? If yes - I don't play it.

**Comment by Mecanik** [comment]
@kyprizel - I Am not playing games, or playing with configs. I have tested this module in and out, on live production with hundreds of websites and thousands of users, and I can tell you even show you people that do not pass the “challenge”. Some people cannot pass check, with JavaScript enabled, with cookies enabled. I tried to debug the module, but I cannot reproduce the problem and find the issue.

People that cannot pass the challenge, they tried chrome,firefox,edge, everything. Some people could pass with internet explorer, which doesn’t make ANY sense.

If you don’t want to continue with this module, then fine at least let me/us know. If you do want to continue, then help us with this issues and I shall personally make you a nice fat donation.

**Comment by kyprizel** [comment]
How can I debug anything if you provide 0 information? I need at least:
1. Example of your configuration
2. Dump of traffic from users having a problem
3. Nginx debug log

P.S. I maintained this module for a couple of years already, you use it "with hundreds of websites and thousands of users" but I never got any donations from anyone. So, please, stop talking about it.

**Comment by Mecanik** [comment]
I shall provide you all the information you need, although some are quite confidential so it would be better to email it.

You probably did not receive yet anything regarding donations, but you will if you try and help people instead of being angry all the time...
