### ISSUE TITLE
one time 307,then 200 OK

### ISSUE THREAD

**Issue by jun283** [kyprizel/testcookie-nginx-module#49]
new install, nginx1.10.2+centos6.5

curl -IL  http://47.91.179.176 -H "host:www.655644633.com"
<pre>
HTTP/1.1 307 Temporary Redirect
Server: TFCDN-1.10.2
Date: Tue, 14 Feb 2017 12:34:59 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 187
Connection: keep-alive
Keep-Alive: timeout=120
Set-Cookie: toffscdn_48c61463-8526-4877-85da-8bd34c06882a=d8818df614d5a2ae479c78731ab15d4b; path=/
Location: http://www.655644633.com/?_tfcdnCCID=1
Expires: Tue, 14 Feb 2017 12:34:58 GMT
Cache-Control: no-cache
ACDN-Toffstech-Version: 2017
X-Remote-Addr: 220.255.95.68

HTTP/1.1 200 OK
Server: TFCDN-1.10.2
Date: Tue, 14 Feb 2017 12:34:59 GMT
Content-Type: text/html; charset=UTF-8
Content-Length: 176
Connection: keep-alive
Keep-Alive: timeout=120
Last-Modified: Mon, 30 May 2016 19:31:44 GMT
ETag: "20e071f-b0-534144e79c528"
Accept-Ranges: bytes
Expires: Tue, 14 Feb 2017 12:34:58 GMT
Cache-Control: no-cache
ACDN-Toffstech-Version: 2017
X-Remote-Addr: 220.255.95.68
</pre>

conf:
<pre>
server
{
 listen 80;
 listen 443 ssl;
................

testcookie on;testcookie_name TFCDNCK_48c61463-8526-4877-85da-8bd34c06882a;testcookie_arg tfcdnCCID;testcookie_secret 48c61463-8526-4877-85da-8bd34c06882a;testcookie_session $remote_addr$http_user_agent;

..............
 location /
 {
 include /ALSvrMrg/SoftProgram/nginx/conf/_c_proxy.conf;

  proxy_no_cache 1;
  expires -1;
  proxy_pass http://a_23d961d4-0c42-454f-a36b-ff753ba8a7d8;
  break; 
 }
 location ~* /purge(/.*)
 {
..................
</pre>

**Comment by kyprizel** [comment]
Is it for HEAD method only?

**Comment by jun283** [comment]
not for HEAD method only,

**Comment by jun283** [comment]
If I test:

curl   http://47.91.179.176 -H "host:www.655644633.com" -L

will direct to origin

**Comment by jun283** [comment]
very strange, same nginx server and same conf, www.9y9e.com is normal, 5 time 307,then return 403

curl   http://47.91.179.176 -H "host:www.9y9e.com" -IL

**Comment by kyprizel** [comment]
Have you tried different nginx versions?
Can I see (may be by email)
$ nginx -V

**Comment by jun283** [comment]
nginx -V
-bash: nginx: command not found
[root@aliyun07 Bin]# ./nginx -V
nginx version: TFCDN-1.10.2
built by gcc 4.4.7 20120313 (Red Hat 4.4.7-17) (GCC) 
built with OpenSSL 1.0.2j  26 Sep 2016
TLS SNI support enabled
configure arguments: --prefix=/ALSvrMrg/SoftProgram/nginx --error-log-path=/ALSvrMrg/SoftProgram/nginx/logs/error.log --http-log-path=/ALSvrMrg/SoftProgram/nginx/logs/access.log --http-client-body-temp-path=/ALSvrMrg/SoftProgram/nginx/client_body_temp --http-proxy-temp-path=/ALSvrMrg/SoftProgram/nginx/temp/ --http-fastcgi-temp-path=/ALSvrMrg/SoftProgram/nginx/fastcgi_temp --http-uwsgi-temp-path=/ALSvrMrg/SoftProgram/nginx/uwsgi_temp --http-scgi-temp-path=/ALSvrMrg/SoftProgram/nginx/uwsgi_temp --user=www --group=www --with-poll_module --with-http_auth_request_module --with-http_image_filter_module --with-file-aio --with-ipv6 --with-http_ssl_module --with-http_realip_module --with-http_addition_module --with-http_xslt_module --with-http_image_filter_module --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_gzip_static_module --with-http_gunzip_module --with-http_random_index_module --with-http_realip_module --with-pcre-jit --with-http_dav_module --with-http_mp4_module --with-http_stub_status_module --with-http_geoip_module --with-http_degradation_module --with-debug --with-pcre=/ALSvrMrg/InstallSource/pcre-8.38 --with-perl=/ALSvrMrg/InstallSource/perl-5.22.1 --with-openssl=/ALSvrMrg/InstallSource/openssl-1.0.2j --add-module=../ngx_rtmp --add-module=../ngx_cache_purge --add-module=../nginx-upstream-fair --add-module=/ALSvrMrg/InstallSource/testcookie-nginx-module

**Comment by jun283** [comment]
curl -x http://47.91.179.176:80 www.655644633.com -IL

this is correct command
