### ISSUE TITLE
not log info

### ISSUE THREAD

**Issue by jun283** [kyprizel/testcookie-nginx-module#50]
We test this module, everything  is normal, very thank contributors.

Only not log info. can not find 302/307 in log files. This is my log config:

http{
..........
log_format test 		'{S;}$remote_addr{S;}$remote_user{S;}$time_local{S;}'
						'$request{S;}$status{S;}$body_bytes_sent{S;}$bytes_sent{S;}'
                        '$http_referer{S;}$http_user_agent{S;}$gzip_ratio{S;}'
                        '$upstream_connect_time{S;}$upstream_response_time{S;}$host';

 access_log syslog:server=52.76.xx.xx:5569,facility=local7,tag=nginx,severity=debug test ;
..........

**Comment by kyprizel** [comment]
It's intentional
