### ISSUE TITLE
nginx 1.10.3 with openssl-1.1.0e compilation issues

### ISSUE THREAD

**Issue by Anton-Kartashev** [kyprizel/testcookie-nginx-module#51]
When compile subj with testcookie-nginx-module cc failed with error:

cc -c -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g '-D FD_SETSIZE=32768'  -I src/core -I src/event -I src/event/modules -I src/os/unix -I /usr/local/src/openssl-1.1.0e/.openssl/include -I objs -I src/http -I src/http/modules -I src/http/v2 \
	-o objs/addon/src/ngx_http_testcookie_access_module.o \
	/usr/src/testcookie-nginx-module/src/ngx_http_testcookie_access_module.c
cc -c -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g '-D FD_SETSIZE=32768' -I src/core -I src/event -I src/event/modules -I src/os/unix -I /usr/local/src/openssl-1.1.0e/.openssl/include -I objs \
	-o objs/ngx_modules.o \
	objs/ngx_modules.c
/usr/src/testcookie-nginx-module/src/ngx_http_testcookie_access_module.c: In function 'ngx_http_testcookie_enc_set_variable':
/usr/src/testcookie-nginx-module/src/ngx_http_testcookie_access_module.c:929:33: error: storage size of 'evp_ctx' isn't known
     EVP_CIPHER_CTX              evp_ctx;
                                 ^
/usr/src/testcookie-nginx-module/src/ngx_http_testcookie_access_module.c:929:33: error: unused variable 'evp_ctx' [-Werror=unused-variable]
cc1: all warnings being treated as errors
make[1]: *** [objs/addon/src/ngx_http_testcookie_access_module.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory `/usr/local/directadmin/custombuild/nginx-1.10.3'
make: *** [build] Error 2

**Comment by kyprizel** [comment]
https://github.com/kyprizel/testcookie-nginx-module/commit/41e3ce39681749ffd34b8b0b0ab10209341469f2

should fix it.

**Comment by Anton-Kartashev** [comment]
Спасибо, Эльдар за быструю реакцию.
