### ISSUE TITLE
Meta refresh content overridden?

### ISSUE THREAD

**Issue by qarizma** [kyprizel/testcookie-nginx-module#54]
Hello,

I want to show a message to visitors before they get redirected, so I have adjusted the value 0 to like 5 seconds in https://github.com/kyprizel/testcookie-nginx-module/blob/master/src/ngx_http_testcookie_access_module.c#L139

But it seems it gets overridden? Is this a bug or am I missing something?

Thanks!

**Comment by kyprizel** [comment]
Better use testcookie_refresh_template
https://github.com/kyprizel/testcookie-nginx-module/blob/master/doc/usecases.txt#L47

**Comment by qarizma** [comment]
I'm already using refresh_template but I just want to delay the redirect, how can I do that?

This seems not to be working when I add it to the template:
`<meta http-equiv="refresh" content="5; URL=$testcookie_nexturl">`

Thanks
