### ISSUE TITLE
Whitelisting huge IP list with "map" problematic

### ISSUE THREAD

**Issue by Mecanik** [kyprizel/testcookie-nginx-module#55]
I have tried to whitelist a huge IP list ( google, yandex, etc ) using map and it doesnt work if you have "100.43.64.0/20" for example.

However, if you use 

```
testcookie_whitelist {
100.43.64.0/20;
}
```

It works, but even so problems appear when you have over 500 IP's there...

What solution is there ? Google+Bing+Yandex = over 1000+ IP's and whitelist is really necessary...

Maybe "map" would work faster and better if subnets would work ?

**Comment by kyprizel** [comment]
may be. you can use variable to disable/enable cookie testing.

**Comment by Mecanik** [comment]
I need enabled permanent... this is why I need whitelist.

**Comment by Mecanik** [comment]
@hroost Thanks, but I'm not aware how else to do it... I cannot block all the social media because of this, and using the module is something I would really like to. Shame because of this issue... I will maybe look into LUA...
