### ISSUE TITLE
There aren’t any releases here

### ISSUE THREAD

**Issue by madest92** [kyprizel/testcookie-nginx-module#61]
@kyprizel can you add the master code to a stable release?

**Comment by kyprizel** [comment]
what for?

**Comment by kyprizel** [comment]
You can make all freezes at your side.

**Comment by dvershinin** [comment]
@kyprizel I don't think it's a lot of extra work to go to Releases tab and tag a release :)
You do have some versions specified in the [changelog](https://github.com/kyprizel/testcookie-nginx-module/blob/master/Changelog#L4) but go figure which one maps to which commit.

Tagging releases would tremendously help with packaging the module as dynamic one, as RPM package. E.g. for [here](https://extras.getpagespeed.com/redhat/7/x86_64/repoview/letter_n.group.html)
