### ISSUE TITLE
problem with Google analytics

### ISSUE THREAD

**Issue by Karmashkin** [kyprizel/testcookie-nginx-module#63]
problem found with Google analytics
1. the referer is lost (which is expected after checking for a cookie and redirection)
2. as a result of the analyst is incorrect
(most of the requests become "direct traffic")

is it possible to store the referrer and send it with a redirect?

thank you for your time,
with sincere respect, Vlad.

**Comment by kyprizel** [comment]
No, it's HTTP protocol specifics.
